blank_issues_enabled: false
contact_links:
  - name: ❓ Discussion
    url: https://github.com/mattieserver/netbox-topology-views/discussions
    about: "If you're just looking for help, try starting a discussion instead"
